pipelines:
  spike-carter-autofac:
    group: spikes
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:spikes/spike-carter-autofac.git"
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              elastic_profile_id: w.c2.m2048.e10
              tasks:
               - exec:
                  command: ide
                  arguments:
                    - "./build.sh"
